= Deployment Guide
:page-children: installation-deployment, solr-control-script-reference, monitoring-solr, circuit-breakers, rate-limiters, client-apis
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

[.lead]
The Deployment Guide covers installation, upgrades, deployments, monitoring, and client integrations.

<<installation-deployment.adoc#installation-deployment,*Installation and Deployment*>>:

// This pulls the sub-section list from the child page to reduce errors
include::installation-deployment.adoc[tag=install-sections]

<<solr-control-script-reference.adoc#solr-control-script-reference,*Solr Control Script Reference*>>: This section provides information about all of the options available to the `bin/solr` / `bin\solr.cmd` scripts, which can start and stop Solr, configure authentication, and create or remove collections and cores.

<<monitoring-solr.adoc#monitoring-solr,*Monitoring Solr*>>: Solr includes options for keeping an eye on the performance of your Solr cluster with the web-based administration console, through the command line interface, or using REST APIs.

// This pulls the sub-section list from the child page to reduce errors
include::monitoring-solr.adoc[tag=monitoring-sections]

<<circuit-breakers.adoc#circuit-breakers,*Circuit Breakers*>>: *TODO* description

<<rate-limiters.adoc#rate-limiters,*Request Rate Limiters*>> *TODO* description

<<client-apis.adoc#client-apis,*Client APIs*>>: This section tells you how to access Solr through various client APIs, including JavaScript, JSON, and Ruby.

// This pulls the sub-section list from the child page to reduce errors
include::client-apis.adoc[tag=client-sections]
