= Documents, Fields, and Schema Design
:page-children: solr-field-types, \
    defining-fields, \
    copying-fields, \
    dynamic-fields, \
    docvalues
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

This section discusses how Solr organizes its data into documents and fields, as well as how to work with a schema in Solr.

This section includes the following topics:

// This tags the below list so it can be used in the parent page section list
// tag::fields-sections[]
* <<solr-field-types.adoc#solr-field-types,Solr Field Types>>: Detailed information about field types in Solr, including the field types in the default Solr schema.

* <<defining-fields.adoc#defining-fields,Defining Fields>>: Describes how to define fields in Solr.

* <<copying-fields.adoc#copying-fields,Copying Fields>>: Describes how to populate fields with data copied from another field.

* <<dynamic-fields.adoc#dynamic-fields,Dynamic Fields>>: Information about using dynamic fields in order to catch and index fields that do not exactly conform to other field definitions in your schema.

* <<docvalues.adoc#docvalues,DocValues>>: Describes how to create a docValues index for faster lookups.
// end::fields-sections[]
